name: www_api
description: https://db.chgk.info/ API
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.2
  html: ^0.15.0
  injectable: ^1.4.1
  json_serializable: ^4.1.3
  www_background_runner:
    path: ../www_background_runner
  www_constants:
    path: ../www_constants/
  www_di:
    path: ../www_di/
  www_http:
    path: ../www_http
  www_models:
    path: ../www_models
  www_utils:
    path: ../www_utils
  xml2json: ^5.3.1

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  mocktail: ^0.1.4
  www_analysis:
    path: ../www_analysis
