name: www_api
description: https://db.chgk.info/ API
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  html: ^0.15.0
  injectable: ^1.5.3
  json_annotation: ^4.7.0
  www_background_runner:
    path: ../www_background_runner
  www_constants:
    path: ../www_constants/
  www_di:
    path: ../www_di/
  www_http:
    path: ../www_http
  www_models:
    path: ../www_models
  www_utils:
    path: ../www_utils
  xml2json: ^5.3.5

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  injectable_generator: ^1.5.4
  json_serializable: ^6.4.1
  www_analysis:
    path: ../www_analysis
  www_test_utils:
    path: ../www_test_utils

dependency_overrides:
  analyzer: 4.7.0