name: www_navigation
description: Pages navigation mechanism
publish_to: none

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  dartx: ^1.2.0
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.1
  injectable: 2.4.2
  www_about:
    path: ../../feature/www_about
  www_analytics:
    path: ../../utils/www_analytics
  www_bookmarks:
    path: ../../feature/www_bookmarks
  www_di:
    path: ../../utils/www_di
  www_image_details:
    path: ../../feature/www_image_details
  www_latest_tournaments:
    path: ../../feature/www_latest_tournaments
  www_questions:
    path: ../../feature/www_questions
  www_redux:
    path: ../../utils/www_redux
  www_redux_actions:
    path: ../../feature/shared/www_redux_actions
  www_settings:
    path: ../../feature/www_settings
  www_tournament_details:
    path: ../../feature/www_tournament_details
  www_tournaments_search:
    path: ../../feature/www_tournaments_search
  www_tournaments_tree:
    path: ../../feature/www_tournaments_tree

dev_dependencies:
  build_runner: 2.4.11
  flutter_test:
    sdk: flutter
  freezed: 2.5.2
  injectable_generator: 2.6.1
  www_analysis:
    path: ../../utils/www_analysis
