name: www_timer
description: Timer feature
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  audioplayers: ^5.0.0
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.1
  injectable: 2.4.2
  path_provider: ^2.0.15
  vibration: ^1.8.1
  www_analytics:
  www_di:
  www_models:
  www_redux:
  www_redux_actions:
  www_settings:
  www_theme:
  www_utils:
  www_widgets:

dev_dependencies:
  build_runner: 2.4.11
  injectable_generator: 2.6.1
  www_analysis:
    
