name: www_image_details
description: Zoomed-in image page
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  photo_view: ^0.14.0
  www_theme:

dev_dependencies:
  www_analysis:
    
