name: www_browsing
description: An open-in-browser feature
publish_to: none

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  flutter:
    sdk: flutter
  injectable: 2.4.2
  url_launcher: ^6.1.12
  www_analytics:
    path: ../../utils/www_analytics
  www_constants:
    path: ../../core/www_constants
  www_di:
    path: ../../utils/www_di
  www_redux:
    path: ../../utils/www_redux
  www_redux_actions: 
    path: ../shared/www_redux_actions

dev_dependencies:
  build_runner: 2.4.11
  injectable_generator: 2.6.1
  www_analysis:
    path: ../../utils/www_analysis
