name: www_browsing
description: An open-in-browser feature
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.1.1
  url_launcher: ^6.1.12
  www_analytics:
    path: ../../utils/www_analytics
  www_constants:
    path: ../../core/www_constants
  www_di:
    path: ../../utils/www_di
  www_redux:
    path: ../../utils/www_redux
  www_redux_actions:
    path: ../../domain/www_redux_actions

dev_dependencies:
  build_runner: ^2.4.6
  injectable_generator: ^2.1.5
  www_analysis:
    path: ../../utils/www_analysis