name: www_redux
description: Base Redux abstractions
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.3'

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0

dev_dependencies:
  www_analysis:
    path: ../www_analysis/