name: www_redux
description: Base Redux abstractions
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0

dev_dependencies:
  www_analysis:
    path: ../www_analysis/