name: www_redux
description: Base Redux abstractions
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  dartz: ^0.10.0
  flutter:
    sdk: flutter
  flutter_redux: ^0.8.2

dev_dependencies:
  www_analysis:
    path: ../www_analysis/