name: www_redux
description: Base Redux abstractions
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0

dev_dependencies:
  www_analysis:
    
