name: www_tournament_status
description: Tournaments history and bookmark status
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.3'

dependencies:
  flutter:
    sdk: flutter
  injectable: ^1.5.3
  www_di:
    path: ../www_di/
  www_local_storage:
    path: ../www_local_storage
  www_models:
    path: ../www_models
  www_utils:
    path: ../www_utils

dev_dependencies:
  build_runner: ^2.2.1
  injectable_generator: ^1.5.4
  www_analysis:
    path: ../www_analysis
