name: www_local_storage
description: A local storage for all www_* packages
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: 2.4.2
  www_analytics:
  www_di:
  www_models:

dev_dependencies:
  build_runner: 2.4.11
  freezed: 2.5.2
  hive_generator: ^2.0.0
  injectable_generator: 2.6.1
  www_analysis:
    
