name: www_local_storage
description: A local storage for all www_* packages
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.1
  www_analytics:
    path: ../../utils/www_analytics
  www_di:
    path: ../../utils/www_di/
  www_models:
    path: ../www_models

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.5
  www_analysis:
    path: ../../utils/www_analysis
