name: www_analytics
description: Analytics and Crashlytics for www_* packages
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  firebase_analytics: ^9.3.7
  firebase_core: ^1.24.0
  firebase_crashlytics: ^2.8.12
  flutter:
    sdk: flutter
  injectable: ^1.5.3
  www_di:
    path: ../www_di/
  www_logger:
    path: ../www_logger/

dev_dependencies:
  build_runner: ^2.2.1
  injectable_generator: ^1.5.4
  www_analysis:
    path: ../www_analysis
