name: www_analytics
description: Analytics and Crashlytics for www_* packages
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.3'

dependencies:
  firebase_analytics: ^8.3.3
  firebase_crashlytics: ^2.2.2
  flutter:
    sdk: flutter
  injectable: ^1.5.3
  www_di:
    path: ../www_di/
  www_logger:
    path: ../www_logger/

dev_dependencies:
  build_runner: ^2.2.1
  injectable_generator: ^1.5.4
  www_analysis:
    path: ../www_analysis
