name: www_localization
description: Localization resources for www_* packages
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  i69n: ^2.1.0

dev_dependencies:
  build_runner: 2.4.11
  www_analysis:
    
