name: www_app_di
description: Dependency inversion container for WWW app
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  www_analytics:
  www_api:
  www_background_runner:
  www_bookmarks:
  www_browsing:
  www_cache:
  www_di:
  www_dialogs:
  www_http:
  www_initialization:
  www_latest_tournaments:
  www_local_storage:
  www_navigation:
  www_preferences:
  www_questions:
  www_rating:
  www_redux_store:
  www_settings:
  www_sharing:
  www_timer:
  www_tournament_details:
  www_tournament_status:
  www_tournament_tours:
  www_tournaments_search:
  www_tournaments_tree:

dev_dependencies:
  www_analysis:
