name: www_app_di
description: Dependency inversion container for WWW app
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  flutter:
    sdk: flutter
  www_analytics:
    path: ../../utils/www_analytics
  www_api:
    path: ../../domain/www_api
  www_background_runner:
    path: ../../utils/www_background_runner
  www_bookmarks:
    path: ../../feature/www_bookmarks
  www_browsing:
    path: ../../feature/www_browsing
  www_cache:
    path: ../../domain/www_cache
  www_di:
    path: ../../utils/www_di
  www_dialogs:
    path: ../../utils/www_dialogs
  www_http:
    path: ../../core/www_http
  www_initialization:
    path: ../../feature/www_initialization
  www_latest_tournaments:
    path: ../../feature/www_latest_tournaments
  www_local_storage:
    path: ../../domain/www_local_storage
  www_navigation:
    path: ../www_navigation
  www_preferences:
    path: ../../utils/www_preferences
  www_questions:
    path: ../../feature/www_questions
  www_rating:
    path: ../../feature/www_rating
  www_redux_store:
    path: ../www_redux_store
  www_settings:
    path: ../../feature/www_settings
  www_sharing:
    path: ../../feature/www_sharing
  www_timer:
    path: ../../feature/www_timer
  www_tournament_details:
    path: ../../feature/www_tournament_details
  www_tournament_status:
    path: ../../feature/www_tournament_status
  www_tournament_tours:
    path: ../../feature/www_tournament_tours
  www_tournaments_search:
    path: ../../feature/www_tournaments_search
  www_tournaments_tree:
    path: ../../feature/www_tournaments_tree

dev_dependencies:
  www_analysis:
    path: ../../utils/www_analysis

dependency_overrides:
  package_info_plus: 4.1.0   # caused by app_review: 2.1.2+1
