name: www_theme
description: Theme and styles for www_* features
publish_to: none

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  www_analysis:
    path: ../../utils/www_analysis
