name: www_navigation
description: Pages navigation mechanism
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  dartx: ^0.7.1
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.2
  injectable: ^1.4.1
  www_about:
    path: ../www_about
  www_analytics:
    path: ../www_analytics
  www_bookmarks:
    path: ../www_bookmarks
  www_di:
    path: ../www_di
  www_image_details:
    path: ../www_image_details
  www_latest_tournaments:
    path: ../www_latest_tournaments
  www_questions:
    path: ../www_questions
  www_redux:
    path: ../www_redux
  www_redux_actions:
    path: ../www_redux_actions
  www_settings:
    path: ../www_settings
  www_tournament_details:
    path: ../www_tournament_details
  www_tournaments_search:
    path: ../www_tournaments_search
  www_tournaments_tree:
    path: ../www_tournaments_tree

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  www_analysis:
    path: ../www_analysis
