name: www_navigation
description: Pages navigation mechanism
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  dartx: ^1.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  injectable: ^1.5.3
  www_about:
    path: ../www_about
  www_analytics:
    path: ../www_analytics
  www_bookmarks:
    path: ../www_bookmarks
  www_di:
    path: ../www_di
  www_image_details:
    path: ../www_image_details
  www_latest_tournaments:
    path: ../www_latest_tournaments
  www_questions:
    path: ../www_questions
  www_redux:
    path: ../www_redux
  www_redux_actions:
    path: ../www_redux_actions
  www_settings:
    path: ../www_settings
  www_tournament_details:
    path: ../www_tournament_details
  www_tournaments_search:
    path: ../www_tournaments_search
  www_tournaments_tree:
    path: ../www_tournaments_tree

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  injectable_generator: ^1.5.4
  www_analysis:
    path: ../www_analysis

dependency_overrides:
  analyzer: 4.7.0

