name: www_app
description: What? When? Where?
version: 2.3.1+20301
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.3'

dependencies:
  flutter:
    sdk: flutter
  www_app_di:
    path: ../www_app_di
  www_widgets:
    path: ../www_widgets

dev_dependencies:
  www_analysis:
    path: ../www_analysis/

flutter:
  uses-material-design: true
  assets:
    - assets/
