name: www_api
description: https://db.chgk.info/ API
publish_to: none

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  html: ^0.15.4
  injectable: ^2.1.1
  json_annotation: ^4.8.1
  www_background_runner:
    path: ../../utils/www_background_runner
  www_constants:
    path: ../../core/www_constants/
  www_di:
    path: ../../utils/www_di/
  www_http:
    path: ../../core/www_http
  www_models:
    path: ../www_models
  www_utils:
    path: ../../utils/www_utils
  xml2json: ^6.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  injectable_generator: ^2.1.5
  json_serializable: ^6.7.1
  www_analysis:
    path: ../../utils/www_analysis
  www_test_utils:
    path: ../../utils/www_test_utils
