name: www_api
description: https://db.chgk.info/ API
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.1
  html: ^0.15.4
  injectable: 2.4.2
  json_annotation: 4.9.0
  www_background_runner:
  www_constants:
  www_di:
  www_http:
  www_models:
  www_utils:
    
  xml2json: ^6.2.3

dev_dependencies:
  build_runner: 2.4.11
  flutter_test:
    sdk: flutter
  freezed: 2.5.2
  injectable_generator: 2.6.1
  json_serializable: 6.8.0
  www_analysis:
  www_test_utils:
    
