name: www_analysis
description: A set of code analysis rules for www_* packages
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  extra_pedantic: 1.2.0
  flutter:
    sdk: flutter
