name: www_initialization
description: App initialization
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  dartx: ^1.2.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  injectable: ^2.1.1
  www_analytics:
    path: ../../utils/www_analytics
  www_background_runner:
    path: ../../utils/www_background_runner
  www_cache:
    path: ../../domain/www_cache
  www_di:
    path: ../../utils/www_di
  www_local_storage:
    path: ../../domain/www_local_storage
  www_redux:
    path: ../../utils/www_redux
  www_redux_actions:
    path: ../shared/www_redux_actions
  www_timer:
    path: ../www_timer

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  injectable_generator: ^2.1.5
  www_analysis:
    path: ../../utils/www_analysis
