name: www_redux_store
description: WWW app Redux store
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.1
  injectable: 2.4.2
  www_bookmarks:
  www_browsing:
  www_di:
  www_initialization:
  www_latest_tournaments:
  www_navigation:
  www_questions:
  www_rating:
  www_redux:
  www_settings:
  www_sharing:
  www_timer:
  www_tournament_details:
  www_tournament_tours:
  www_tournaments_search:
  www_tournaments_tree:
    
dev_dependencies:
  build_runner: 2.4.11
  freezed: 2.5.2
  injectable_generator: 2.6.1
  www_analysis:
  www_test_utils:
