name: www_preferences
description: App preferences storage
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.3'

dependencies:
  flutter:
    sdk: flutter
  injectable: ^1.5.3
  shared_preferences: ^2.0.15
  www_analytics:
    path: ../www_analytics
  www_di:
    path: ../www_di/

dev_dependencies:
  build_runner: ^2.2.1
  injectable_generator: ^1.5.4
  www_analysis:
    path: ../www_analysis/