name: www_http
description: Http client
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  injectable: ^1.5.3
  www_constants:
    path: ../www_constants/
  www_di:
    path: ../www_di/
  www_logger:
    path: ../www_logger/
  www_utils:
    path: ../www_utils

dev_dependencies:
  build_runner: ^2.2.1
  injectable_generator: ^1.5.4
  www_analysis:
    path: ../www_analysis/