name: www_constants
description: Application constants
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.3'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  www_analysis:
    path: ../www_analysis/