name: www_utils
description: Misc utils
publish_to: none

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  flutter:
    sdk: flutter
  html_unescape: ^2.0.0

dev_dependencies:
  www_analysis:
    path: ../www_analysis
