name: www_latest_tournaments
description: Latest tournaments list feature
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5
  freezed_annotation: ^2.1.0
  injectable: ^1.5.3
  www_analytics:
    path: ../www_analytics
  www_api:
    path: ../www_api/
  www_custom_icons:
    path: ../www_custom_icons/
  www_di:
    path: ../www_di/
  www_localization:
    path: ../www_localization
  www_models:
    path: ../www_models/
  www_redux:
    path: ../www_redux/
  www_redux_actions:
    path: ../www_redux_actions/
  www_theme:
    path: ../www_theme
  www_tournament_status:
    path: ../www_tournament_status/
  www_widgets:
    path: ../www_widgets/

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.1
  injectable_generator: ^1.5.4
  www_analysis:
    path: ../www_analysis/
  www_test_utils:
    path: ../www_test_utils

dependency_overrides:
  analyzer: 4.7.0
