name: www_settings
description: WWW app settings feature
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  injectable: 2.4.2
  www_analytics:
  www_di:
  www_localization:
  www_preferences:
  www_redux:
  www_redux_actions:
  www_theme:
  www_widgets:

dev_dependencies:
  build_runner: 2.4.11
  injectable_generator: 2.6.1
  www_analysis:
    
