name: www_questions
description: Questions list feature
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ^0.10.3
  freezed_annotation: ^2.4.1
  injectable: ^2.1.1
  www_analytics:
    path: ../www_analytics
  www_api:
    path: ../www_api/
  www_di:
    path: ../www_di/
  www_dialogs:
    path: ../www_dialogs/
  www_localization:
    path: ../www_localization
  www_models:
    path: ../www_models/
  www_redux:
    path: ../www_redux/
  www_redux_actions:
    path: ../www_redux_actions/
  www_theme:
    path: ../www_theme
  www_timer:
    path: ../www_timer
  www_utils:
    path: ../www_utils/
  www_widgets:
    path: ../www_widgets/

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  injectable_generator: ^2.1.5
  www_analysis:
    path: ../www_analysis/
  www_test_utils:
    path: ../www_test_utils
