name: www_tournament_details
description: Tournament details feature
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.3'

dependencies:
  dartx: ^1.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  injectable: ^1.5.3
  www_analytics:
    path: ../www_analytics
  www_api:
    path: ../www_api/
  www_cache:
    path: ../www_cache/
  www_di:
    path: ../www_di/
  www_dialogs:
    path: ../www_dialogs/
  www_localization:
    path: ../www_localization
  www_models:
    path: ../www_models/
  www_redux:
    path: ../www_redux/
  www_redux_actions:
    path: ../www_redux_actions/
  www_theme:
    path: ../www_theme
  www_tournament_status:
    path: ../www_tournament_status/
  www_tournament_tours:
    path: ../www_tournament_tours/
  www_widgets:
    path: ../www_widgets/

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.1
  injectable_generator: ^1.5.4
  www_analysis:
    path: ../www_analysis/
  www_test_utils:
    path: ../www_test_utils

dependency_overrides:
  analyzer: 4.7.0
