name: www_tournament_details
description: Tournament details feature
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  dartx: ^1.2.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  injectable: ^2.1.1
  www_analytics:
    path: ../www_analytics
  www_api:
    path: ../www_api/
  www_cache:
    path: ../www_cache/
  www_di:
    path: ../www_di/
  www_dialogs:
    path: ../www_dialogs/
  www_localization:
    path: ../www_localization
  www_models:
    path: ../www_models/
  www_redux:
    path: ../www_redux/
  www_redux_actions:
    path: ../www_redux_actions/
  www_theme:
    path: ../www_theme
  www_tournament_status:
    path: ../www_tournament_status/
  www_tournament_tours:
    path: ../www_tournament_tours/
  www_widgets:
    path: ../www_widgets/

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  injectable_generator: ^2.1.5
  www_analysis:
    path: ../www_analysis/
  www_test_utils:
    path: ../www_test_utils
