name: www_tournament_status
description: Tournaments history and bookmark status
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  injectable: 2.4.2
  www_di:
  www_local_storage:
  www_models:
  www_utils:

dev_dependencies:
  build_runner: 2.4.11
  injectable_generator: 2.6.1
  www_analysis:
    
