name: www_analysis
description: A set of code analysis rules for www_* packages
publish_to: none

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  extra_pedantic: ^4.0.0
  flutter:
    sdk: flutter
