name: www_cache
description: An in-memory cache for all www_* packages
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  injectable: ^1.4.1
  www_analytics:
    path: ../www_analytics
  www_di:
    path: ../www_di/
  www_local_storage:
    path: ../www_local_storage
  www_models:
    path: ../www_models
  www_utils:
    path: ../www_utils

dev_dependencies:
  build_runner: ^2.1.1
  injectable_generator: ^1.4.1
  www_analysis:
    path: ../www_analysis
