name: www_http
description: Http client
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  injectable: 2.4.2
  www_constants:
  www_di:
  www_logger:
  www_utils:

dev_dependencies:
  build_runner: 2.4.11
  injectable_generator: 2.6.1
  www_analysis:
    
