name: www_http
description: Http client
publish_to: none

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  injectable: ^2.1.1
  www_constants:
    path: ../www_constants/
  www_di:
    path: ../../utils/www_di/
  www_logger:
    path: ../../utils/www_logger/
  www_utils:
    path: ../../utils/www_utils

dev_dependencies:
  build_runner: ^2.4.6
  injectable_generator: ^2.1.5
  www_analysis:
    path: ../../utils/www_analysis
