name: www_local_storage
description: A local storage for all www_* packages
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.3'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^1.5.3
  www_analytics:
    path: ../www_analytics
  www_di:
    path: ../www_di/
  www_models:
    path: ../www_models

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.1
  hive_generator: ^1.1.3
  injectable_generator: ^1.5.4
  www_analysis:
    path: ../www_analysis

dependency_overrides:
  analyzer: 4.7.0
