name: www_test_utils
description: Misc utils for testing
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  www_analytics:
    path: ../www_analytics

dev_dependencies:
  www_analysis:
    path: ../www_analysis/