name: www_test_utils
description: Misc utils for testing
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  www_analytics:
    path: ../www_analytics

dev_dependencies:
  www_analysis:
    path: ../www_analysis/