name: www

packages:
  - ./**

scripts:
  generate:
    run: melos exec -c 1 --depends-on="build_runner" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"

  get:
    run: melos exec -- "flutter pub get"

  test:
    run: melos exec --dir-exists="test" -- "flutter test"
