name: what_when_where
description: What? When? Where?

version: 2.2.2+20202
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  www_about:
    path: www_about/
  www_analytics:
    path: www_analytics/
  www_api:
    path: www_api/
  www_background_runner:
    path: www_background_runner/
  www_bookmarks:
    path: www_bookmarks/
  www_browsing:
    path: www_browsing/
  www_cache:
    path: www_cache/
  www_constants:
    path: www_constants/
  www_di:
    path: www_di/
  www_dialogs:
    path: www_dialogs/
  www_http:
    path: www_http/
  www_image_details:
    path: www_image_details/
  www_initialization:
    path: www_initialization/
  www_latest_tournaments:
    path: www_latest_tournaments/
  www_local_storage:
    path: www_local_storage/
  www_localization:
    path: www_localization/
  www_logger:
    path: www_logger/
  www_models:
    path: www_models/
  www_navigation:
    path: www_navigation/
  www_preferences:
    path: www_preferences/
  www_questions:
    path: www_questions/
  www_rating:
    path: www_rating/
  www_redux:
    path: www_redux/
  www_redux_actions:
    path: www_redux_actions/
  www_redux_store:
    path: www_redux_store/
  www_settings:
    path: www_settings/
  www_sharing:
    path: www_sharing/
  www_theme:
    path: www_theme/
  www_timer:
    path: www_timer/
  www_tournament_details:
    path: www_tournament_details/
  www_tournament_status:
    path: www_tournament_status/
  www_tournament_tours:
    path: www_tournament_tours/
  www_tournaments_search:
    path: www_tournaments_search/
  www_tournaments_tree:
    path: www_tournaments_tree/
  www_utils:
    path: www_utils/
  www_widgets:
    path: www_widgets/

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  www_analysis:
    path: www_analysis/

flutter:
  uses-material-design: true
  assets:
    - assets/
