name: www_initialization
description: App initialization
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.3'

dependencies:
  dartx: ^1.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  injectable: ^1.5.3
  www_analytics:
    path: ../www_analytics
  www_background_runner:
    path: ../www_background_runner
  www_cache:
    path: ../www_cache
  www_di:
    path: ../www_di
  www_local_storage:
    path: ../www_local_storage
  www_redux:
    path: ../www_redux
  www_redux_actions:
    path: ../www_redux_actions
  www_timer:
    path: ../www_timer

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  injectable_generator: ^1.5.4
  www_analysis:
    path: ../www_analysis

dependency_overrides:
  analyzer: 4.7.0
