name: www_tournament_tours
description: Tournament tours list feature
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  injectable: ^2.1.1
  www_analytics:
    path: ../../utils/www_analytics
  www_api:
    path: ../../domain/www_api
  www_cache:
    path: ../../domain/www_cache
  www_di:
    path: ../../utils/www_di
  www_localization:
    path: ../../core/www_localization
  www_models:
    path: ../../domain/www_models
  www_redux:
    path: ../../utils/www_redux
  www_redux_actions:
    path: ../shared/www_redux_actions
  www_theme:
    path: ../../design/www_theme
  www_tournament_status:
    path: ../shared/www_tournament_status
  www_widgets:
    path: ../../design/www_widgets

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  injectable_generator: ^2.1.5
  www_analysis:
    path: ../../utils/www_analysis
  www_test_utils:
    path: ../../utils/www_test_utils
