name: www_tournament_tours
description: Tournament tours list feature
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.1
  injectable: 2.4.2
  www_analytics:
  www_api:
  www_cache:
  www_di:
  www_localization:
  www_models:
  www_redux:
  www_redux_actions:
  www_theme:
  www_tournament_status:
  www_widgets:

dev_dependencies:
  build_runner: 2.4.11
  freezed: 2.5.2
  injectable_generator: 2.6.1
  www_analysis:
  www_test_utils:
    
