name: www_redux_actions
description: Redux actions for the entire WWW app
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.2
  www_localization:
    path: ../www_localization
  www_models:
    path: ../www_models
  www_redux:
    path: ../www_redux/

dev_dependencies:
  build_runner: ^2.1.1
  freezed: ^0.14.2
  www_analysis:
    path: ../www_analysis/