name: www_redux_actions
description: Redux actions for the entire WWW app
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  www_localization:
    path: ../www_localization
  www_models:
    path: ../www_models
  www_redux:
    path: ../www_redux/

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  www_analysis:
    path: ../www_analysis/
