name: www_app
description: What? When? Where?
version: 2.3.1+20301
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  www_app_di:
  www_widgets:

dev_dependencies:
  www_analysis:

flutter:
  uses-material-design: true
  assets:
    - assets/
