name: www_app
description: What? When? Where?
version: 2.3.1+20301
publish_to: none

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  flutter:
    sdk: flutter
  www_app_di:
    path: ../www_app_di
  www_widgets:
    path: ../../design/www_widgets

dev_dependencies:
  www_analysis:
    path: ../../utils/www_analysis

flutter:
  uses-material-design: true
  assets:
    - assets/

dependency_overrides:
  package_info_plus: 4.1.0   # caused by app_review: 2.1.2+1
