name: www_questions
description: Questions list feature
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ^0.10.3
  freezed_annotation: 2.4.1
  injectable: 2.4.2
  www_analytics:
  www_api:
  www_di:
  www_dialogs:
  www_localization:
  www_models:
  www_redux:
  www_redux_actions:
  www_theme:
  www_timer:
  www_utils:
  www_widgets:

dev_dependencies:
  build_runner: 2.4.11
  freezed: 2.5.2
  injectable_generator: 2.6.1
  www_analysis:
  www_test_utils:
    
