name: www_questions
description: Questions list feature
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ^0.10.3
  freezed_annotation: ^2.4.1
  injectable: ^2.1.1
  www_analytics:
    path: ../../utils/www_analytics
  www_api:
    path: ../../domain/www_api
  www_di:
    path: ../../utils/www_di
  www_dialogs:
    path: ../../utils/www_dialogs
  www_localization:
    path: ../../core/www_localization
  www_models:
    path: ../../domain/www_models
  www_redux:
    path: ../../utils/www_redux
  www_redux_actions:
    path: ../../domain/www_redux_actions
  www_theme:
    path: ../../design/www_theme
  www_timer:
    path: ../www_timer
  www_utils:
    path: ../../utils/www_utils
  www_widgets:
    path: ../../design/www_widgets

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  injectable_generator: ^2.1.5
  www_analysis:
    path: ../../utils/www_analysis
  www_test_utils:
    path: ../../utils/www_test_utils
