name: www_models
description: www_* models
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  dartx: ^0.7.1
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.2

dev_dependencies:
  build_runner: ^2.1.1
  freezed: ^0.14.2
  www_analysis:
    path: ../www_analysis
