name: www_models
description: www_* models
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.3'

dependencies:
  dartx: ^1.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.1
  www_analysis:
    path: ../www_analysis

dependency_overrides:
  analyzer: 4.7.0

