name: www_di
description: Dependency inversion mechanism for www_* packages
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  get_it: 7.7.0
  injectable: 2.4.2
  www_logger:


dev_dependencies:
  build_runner: 2.4.11
  injectable_generator: 2.6.1
  www_analysis:
    
