name: www_di
description: Dependency inversion mechanism for www_* packages
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  injectable: ^2.1.1
  www_logger:
    path: ../www_logger/

dev_dependencies:
  build_runner: ^2.4.6
  injectable_generator: ^2.1.5
  www_analysis:
    path: ../www_analysis
