name: www_redux_actions
description: Redux actions for the entire WWW app
publish_to: none

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.1
  www_localization:
    path: ../../../core/www_localization
  www_models:
    path: ../../../domain/www_models
  www_redux:
    path: ../../../utils/www_redux

dev_dependencies:
  build_runner: 2.4.11
  freezed: 2.5.2
  www_analysis:
    path: ../../../utils/www_analysis
