name: www_redux_actions
description: Redux actions for the entire WWW app
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.1
  www_localization:
  www_models:
  www_redux:

dev_dependencies:
  build_runner: 2.4.11
  freezed: 2.5.2
  www_analysis:
    
