name: www_background_runner
description: Background runner
publish_to: none

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  injectable: ^2.1.1
  isolate: ^2.1.1 #discontinued
  www_di:
    path: ../www_di

dev_dependencies:
  build_runner: ^2.4.6
  injectable_generator: ^2.1.5
  www_analysis:
    path: ../www_analysis
