name: www_background_runner
description: Background runner
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  injectable: 2.4.2
  isolate: ^2.1.1 #discontinued
  www_di:

dev_dependencies:
  build_runner: 2.4.11
  injectable_generator: 2.6.1
  www_analysis:
    
