name: www_test_utils
description: Misc utils for testing
publish_to: none

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  www_analytics:
    path: ../www_analytics

dev_dependencies:
  www_analysis:
    path: ../www_analysis
