name: www_test_utils
description: Misc utils for testing
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  www_analytics:

dev_dependencies:
  www_analysis:
    
