name: www_preferences
description: App preferences storage
publish_to: none

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  flutter:
    sdk: flutter
  injectable: 2.4.2
  shared_preferences: ^2.2.0
  www_analytics:
    path: ../www_analytics
  www_di:
    path: ../www_di

dev_dependencies:
  build_runner: 2.4.11
  injectable_generator: 2.6.1
  www_analysis:
    path: ../www_analysis
