name: www_custom_icons
description: A wrapper over icons font for www_* features
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  www_analysis:
    path: ../../utils/www_analysis

flutter:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf
