name: www_custom_icons
description: A wrapper over icons font for www_* features
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  www_analysis:

flutter:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf
