name: www_custom_icons
description: A wrapper over icons font for www_* features
publish_to: none

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  www_analysis:
    path: ../../utils/www_analysis

flutter:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf
