name: www_image_details
description: Zoomed-in image page
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  cached_network_image: ^3.1.0
  flutter:
    sdk: flutter
  photo_view: ^0.12.0
  www_theme:
    path: ../www_theme

dev_dependencies:
  www_analysis:
    path: ../www_analysis/
