name: www_image_details
description: Zoomed-in image page
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.3'

dependencies:
  cached_network_image: ^3.2.2
  flutter:
    sdk: flutter
  photo_view: ^0.14.0
  www_theme:
    path: ../www_theme

dev_dependencies:
  www_analysis:
    path: ../www_analysis/
