name: www_rating
description: A rate-the-app feature
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  app_review: ^2.1.2+1
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.7
  injectable: ^2.1.1
  www_analytics:
    path: ../www_analytics
  www_di:
    path: ../www_di/
  www_dialogs:
    path: ../www_dialogs/
  www_localization:
    path: ../www_localization
  www_preferences:
    path: ../www_preferences/
  www_redux:
    path: ../www_redux/
  www_redux_actions:
    path: ../www_redux_actions/
  www_theme:
    path: ../www_theme/

dev_dependencies:
  build_runner: ^2.4.6
  injectable_generator: ^2.1.5
  www_analysis:
    path: ../www_analysis/

