name: www_rating
description: A rate-the-app feature
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  app_review: ^2.1.1+1
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^0.22.0
  injectable: ^1.4.1
  www_analytics:
    path: ../www_analytics
  www_di:
    path: ../www_di/
  www_dialogs:
    path: ../www_dialogs/
  www_localization:
    path: ../www_localization
  www_preferences:
    path: ../www_preferences/
  www_redux:
    path: ../www_redux/
  www_redux_actions:
    path: ../www_redux_actions/
  www_theme:
    path: ../www_theme/

dev_dependencies:
  build_runner: ^2.1.1
  injectable_generator: ^1.4.1
  www_analysis:
    path: ../www_analysis/