name: www_redux_store
description: WWW app Redux store
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.2
  injectable: ^1.4.1
  www_bookmarks:
    path: ../www_bookmarks
  www_browsing:
    path: ../www_browsing
  www_di:
    path: ../www_di
  www_initialization:
    path: ../www_initialization
  www_latest_tournaments:
    path: ../www_latest_tournaments
  www_navigation:
    path: ../www_navigation
  www_questions:
    path: ../www_questions
  www_rating:
    path: ../www_rating
  www_redux:
    path: ../www_redux
  www_settings:
    path: ../www_settings
  www_sharing:
    path: ../www_sharing
  www_timer:
    path: ../www_timer
  www_tournament_details:
    path: ../www_tournament_details
  www_tournament_tours:
    path: ../www_tournament_tours
  www_tournaments_search:
    path: ../www_tournaments_search
  www_tournaments_tree:
    path: ../www_tournaments_tree

dev_dependencies:
  build_runner: ^2.1.1
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  www_analysis:
    path: ../www_analysis
