name: www_redux_store
description: WWW app Redux store
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  injectable: ^2.1.1
  www_bookmarks:
    path: ../www_bookmarks
  www_browsing:
    path: ../www_browsing
  www_di:
    path: ../www_di
  www_initialization:
    path: ../www_initialization
  www_latest_tournaments:
    path: ../www_latest_tournaments
  www_navigation:
    path: ../www_navigation
  www_questions:
    path: ../www_questions
  www_rating:
    path: ../www_rating
  www_redux:
    path: ../www_redux
  www_settings:
    path: ../www_settings
  www_sharing:
    path: ../www_sharing
  www_timer:
    path: ../www_timer
  www_tournament_details:
    path: ../www_tournament_details
  www_tournament_tours:
    path: ../www_tournament_tours
  www_tournaments_search:
    path: ../www_tournaments_search
  www_tournaments_tree:
    path: ../www_tournaments_tree

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  injectable_generator: ^2.1.5
  www_analysis:
    path: ../www_analysis
  www_test_utils:
    path: ../www_test_utils

dependency_overrides:
  package_info_plus: 4.1.0   # caused by app_review: 2.1.2+1
