name: www_widgets
description: Common widgets for www_* features
publish_to: none

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  www_localization:
    path: ../../core/www_localization
  www_models:
    path: ../../domain/www_models
  www_theme:
    path: ../www_theme
  www_utils:
    path: ../../utils/www_utils

dev_dependencies:
  www_analysis:
    path: ../../utils/www_analysis
