name: www_timer
description: Timer feature
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.3'

dependencies:
  audioplayers: ^1.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  injectable: ^1.5.3
  path_provider: ^2.0.11
  vibration: ^1.7.6
  www_analytics:
    path: ../www_analytics
  www_di:
    path: ../www_di/
  www_models:
    path: ../www_models/
  www_redux:
    path: ../www_redux/
  www_redux_actions:
    path: ../www_redux_actions/
  www_settings:
    path: ../www_settings
  www_theme:
    path: ../www_theme
  www_utils:
    path: ../www_utils/
  www_widgets:
    path: ../www_widgets/

dev_dependencies:
  build_runner: ^2.2.1
  injectable_generator: ^1.5.4
  www_analysis:
    path: ../www_analysis/

flutter:
  assets:
    - assets/
