name: www_timer
description: Timer feature
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  audioplayers: ^0.19.1
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.2
  injectable: ^1.4.1
  path_provider: ^2.0.2
  vibration: ^1.7.4-nullsafety.0
  www_analytics:
    path: ../www_analytics
  www_di:
    path: ../www_di/
  www_models:
    path: ../www_models/
  www_redux:
    path: ../www_redux/
  www_redux_actions:
    path: ../www_redux_actions/
  www_settings:
    path: ../www_settings
  www_theme:
    path: ../www_theme
  www_utils:
    path: ../www_utils/
  www_widgets:
    path: ../www_widgets/

dev_dependencies:
  build_runner: ^2.1.1
  injectable_generator: ^1.4.1
  www_analysis:
    path: ../www_analysis/

flutter:
  assets:
    - assets/
