name: www_timer
description: Timer feature
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  audioplayers: ^5.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  injectable: ^2.1.1
  path_provider: ^2.0.15
  vibration: ^1.8.1
  www_analytics:
    path: ../www_analytics
  www_di:
    path: ../www_di/
  www_models:
    path: ../www_models/
  www_redux:
    path: ../www_redux/
  www_redux_actions:
    path: ../www_redux_actions/
  www_settings:
    path: ../www_settings
  www_theme:
    path: ../www_theme
  www_utils:
    path: ../www_utils/
  www_widgets:
    path: ../www_widgets/

dev_dependencies:
  build_runner: ^2.4.6
  injectable_generator: ^2.1.5
  www_analysis:
    path: ../www_analysis/
