name: www_background_runner
description: Background runner
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  dartz: ^0.10.0
  flutter:
    sdk: flutter
  injectable: ^1.4.1
  isolate: ^2.1.1 #discontinued
  www_di:
    path: ../www_di/

dev_dependencies:
  build_runner: ^2.1.1
  injectable_generator: ^1.4.1
  www_analysis:
    path: ../www_analysis/