name: www_utils
description: Misc utils
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.3'

dependencies:
  flutter:
    sdk: flutter
  html_unescape: ^2.0.0

dev_dependencies:
  www_analysis:
    path: ../www_analysis/