name: www_constants
description: Application constants
publish_to: none

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  www_analysis:
    path: ../../utils/www_analysis
