name: www_dialogs
description: Dialogs mechanism
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  injectable: ^1.4.1
  www_analytics:
    path: ../www_analytics

dev_dependencies:
  build_runner: ^2.1.1
  injectable_generator: ^1.4.1
  www_analysis:
    path: ../www_analysis/