name: www_rating
description: A rate-the-app feature
publish_to: none

environment:
  sdk: ^3.5.0-180.3.beta
  flutter: ^3.22.1

resolution: workspace

dependencies:
  app_review: ^2.1.2+1
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.7
  injectable: 2.4.2
  www_analytics:
  www_di:
  www_dialogs:
  www_localization:
  www_preferences:
  www_redux:
  www_redux_actions:
  www_theme:

dev_dependencies:
  build_runner: 2.4.11
  injectable_generator: 2.6.1
  www_analysis:

