name: www_localization
description: Localization resources for www_* packages
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  i69n: ^2.1.0

dev_dependencies:
  build_runner: ^2.2.1
  www_analysis:
    path: ../www_analysis/